# Generated by Django 5.2.5 on 2026-01-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_usuario_rol_alter_usuario_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=200)),
                ('creado_en', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventorepertorio',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='eventorepertorio',
            name='repertorio',
        ),
        migrations.RemoveField(
            model_name='parrafo',
            name='repertorio',
        ),
        migrations.RemoveField(
            model_name='rolusuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='rolusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='iglesia',
        ),
        migrations.CreateModel(
            name='inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('img', models.CharField(max_length=200)),
                ('adm', models.BooleanField(default=False)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.comprobante')),
                ('iglesia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.iglesia')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='EventoRepertorio',
        ),
        migrations.DeleteModel(
            name='Parrafo',
        ),
        migrations.DeleteModel(
            name='Repertorio',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='RolUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
