# Generated by Django 5.2.5 on 2026-01-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_administrador_comprobante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='adm',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='img',
        ),
        migrations.RemoveField(
            model_name='inscrito',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='inscrito',
            name='edad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscrito',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=2, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscrito',
            name='pagoComprobante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='pagoFecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='pagoHora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='pagoTelefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iglesia',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='iglesia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.iglesia'),
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
